package com.biodex.server.auth
import com.auth0.jwt.JWT
import com.auth0.jwt.JWTVerifier
import com.auth0.jwt.algorithms.Algorithm
import com.auth0.jwt.exceptions.JWTVerificationException
import com.auth0.jwt.interfaces.DecodedJWT
import java.util.Date

/**
 * Single source of truth for JWT settings across the BioDex Auth & User Service.
 * Security.kt (generated by the Ktor plugin) should reference these same
 * constants for its verifier, so tokens issued here validate correctly
 * on protected routes.
 *
 * NOTE: SECRET is a placeholder for local dev only. In production, load it
 * from an environment variable (e.g. System.getenv("JWT_SECRET")) instead
 * of hard-coding it.
 */
object JwtConfig {

    const val SECRET = "CHANGE_ME_BIODEX_DEV_SECRET" // TODO: move to env var JWT_SECRET
    const val ISSUER = "https://biodex-auth-service/"
    const val AUDIENCE = "biodex-app"
    const val REALM = "biodex-app"

    // 30-day expiration window, expressed in milliseconds
    private const val EXPIRATION_MILLIS: Long = 30L * 24 * 60 * 60 * 1000

    private val algorithm: Algorithm = Algorithm.HMAC256(SECRET)

    val verifier: JWTVerifier = JWT.require(algorithm)
        .withIssuer(ISSUER)
        .withAudience(AUDIENCE)
        .build()

    /**
     * Generates a signed JWT for the given user, valid for 30 days.
     *
     * @param userId Unique user identifier (e.g. "usr_101")
     * @param username The user's display/login username
     * @return signed JWT string
     */
    fun generateToken(userId: String, username: String): String {
        val now = System.currentTimeMillis()
        val expiresAt = Date(now + EXPIRATION_MILLIS)

        return JWT.create()
            .withIssuer(ISSUER)
            .withAudience(AUDIENCE)
            .withClaim("userId", userId)
            .withClaim("username", username)
            .withIssuedAt(Date(now))
            .withExpiresAt(expiresAt)
            .sign(algorithm)
    }

    /**
     * Validates a JWT and returns the decoded token if valid.
     * Returns null if the token is invalid, malformed, or expired.
     */
    fun validateToken(token: String): DecodedJWT? {
        return try {
            verifier.verify(token)
        } catch (e: JWTVerificationException) {
            null
        }
    }

    /**
     * Convenience helper to extract userId from a validated token.
     */
    fun extractUserId(token: String): String? {
        return validateToken(token)?.getClaim("userId")?.asString()
    }
}